language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO=django==1.4.16
  - DJANGO=django==1.5.11
  - DJANGO=django==1.6.8
  - DJANGO=django==1.7.1

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=django==1.7.1
    - python: "3.3"
      env: DJANGO=django==1.4.16
    - python: "3.4"
      env: DJANGO=django==1.4.16

install:
  - pip install -q $DJANGO
  - pip install -q flake8 coveralls coverage
  - python setup.py install

before_script:
  - make flake8

script:
  - make coverage

after_success:
  - make coveralls
